### PR TITLE
Update Firefox to version 70.0-r0

### PR DESCRIPTION
**Pull request by c64bob**

### CODE REVIEW

**Comment by jlesage** [comment]
Thanks for this PR, but unfortunately this version doesn't start due to missing symbol... I'm currently looking for solutions.

**Comment by c64bob** [comment]
That is strange, Firefox was starting in my container. But you're right, there was an error message concerning a missing symbol:

> Executing gtk+3.0-3.24.12-r0.post-install
> Error relocating /usr/lib/libxkbcommon.so.0: secure_getenv: symbol not found

**Comment by jlesage** [comment]
This is the error I get when Firefox is started:
```
XPCOMGlueLoad error for file /usr/lib/firefox/libmozsandbox.so:
Error relocating /usr/lib/firefox/libmozsandbox.so: _ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info: symbol not found
Couldn't load XPCOM.
```

**Comment by c64bob** [comment]
Maybe an update to Alpine 3.10 as bas eimage is needed?

**Comment by jlesage** [comment]
This doesn't help.  I'm currently working on compiling Firefox against a stable version of Alpine.

**Comment by c64bob** [comment]
I think I've found what is causing the errors: when compiling lz4 and jsonlz4, musl is being downgraded. According to [here](https://gitlab.alpinelinux.org/alpine/aports/issues/9947) this causes the resulting errors. The workaround I am using:
- upgrade base image to alpine 3.10
- install lz4 from alpine repository instead of compiling it
- remove jsonlz4 completely, not sure where this is needed.

What are your thoughts?

**Comment by jlesage** [comment]
Thanks for sharing you findings! jsonlz4 is used to fix the Firefox config, so it must be kept.

I didn't notice the musl downgrade... I will look at this.

**Comment by c64bob** [comment]
Awesome, thanks for fixing this!

**Pull request closed without merging**
